/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class ADirective extends PDirective
{
    private PDirname _dirname_;
    private TTDot _tDot_;

    public ADirective()
    {
        // Constructor
    }

    public ADirective(
        @SuppressWarnings("hiding") PDirname _dirname_,
        @SuppressWarnings("hiding") TTDot _tDot_)
    {
        // Constructor
        setDirname(_dirname_);

        setTDot(_tDot_);

    }

    @Override
    public Object clone()
    {
        return new ADirective(
            cloneNode(this._dirname_),
            cloneNode(this._tDot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADirective(this);
    }

    public PDirname getDirname()
    {
        return this._dirname_;
    }

    public void setDirname(PDirname node)
    {
        if(this._dirname_ != null)
        {
            this._dirname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dirname_ = node;
    }

    public TTDot getTDot()
    {
        return this._tDot_;
    }

    public void setTDot(TTDot node)
    {
        if(this._tDot_ != null)
        {
            this._tDot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tDot_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dirname_)
            + toString(this._tDot_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dirname_ == child)
        {
            this._dirname_ = null;
            return;
        }

        if(this._tDot_ == child)
        {
            this._tDot_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dirname_ == oldChild)
        {
            setDirname((PDirname) newChild);
            return;
        }

        if(this._tDot_ == oldChild)
        {
            setTDot((TTDot) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
